import { State } from "./stateTypes";

export let state: State = {
  paused: false,
  playerMaxHealth: 30,
  playerStartingHealth: 30,
  playerHealth: 0,
  playerThrust: 0,
  playerWeaponPower: 0,
  enemyHealth: 0,
  enemyThrust: 0,
  enemyWeaponPower: 0,
  spaceShipsContract: '0xC95D885A85A3fc66F6c2c9511E8769e9CbC70363',
  spaceCoinsContract: '0x393fDB069940aF8E7AFd04ab9D61A0E2Bb474d03',
  ownedShips: [],
  currentShip: {
    tokenId: 0,
    shipCode: '0000',
  },
  currentLevelIndex: 0,
  levelHistory: [],
  spaceCoinsBalance: 0,
  inventory: [],
  shopInventory: [
    'itemCabin0',
    'itemCabin1',
    'itemCabin2',
    'itemCabin3',
    'itemWeapon0',
    'itemWeapon1',
    'itemWeapon2',
    'itemWeapon3',
    'itemWing0',
    'itemWing1',
    'itemWing2',
    'itemWing3',
    'itemEngine0',
    'itemEngine1',
    'itemEngine2',
    'itemEngine3',
  ],
  shipSize: 60,
  itemSize: 50,
}
